import { College, Category, Course, AccessType, Workshop } from '@/types/database';

export const MOCK_COLLEGES: College[] = [
  {
    id: 'c0000000-0000-0000-0000-000000000005',
    name: 'BMS Institute of Technology and Management',
    short_name: 'BMSIT',
    domain: 'bmsit.in',
    logo_url: 'https://images.unsplash.com/photo-1562774053-701939374585?auto=format&fit=crop&w=400&q=80',
    description: 'Autonomous engineering college in Yelahanka, Bangalore, Karnataka with top tech industry partnerships.',
    location: 'Yelahanka, Bangalore, India',
    is_active: true,
    course_count: 13,
  },
  {
    id: 'c0000000-0000-0000-0000-000000000001',
    name: 'Stanford University',
    short_name: 'Stanford',
    domain: 'stanford.edu',
    logo_url: 'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?auto=format&fit=crop&w=400&q=80',
    description: 'Leading research university in Stanford, California with active academic cloud partnerships.',
    location: 'Stanford, CA, USA',
    is_active: true,
    course_count: 13,
  },
  {
    id: 'c0000000-0000-0000-0000-000000000002',
    name: 'Massachusetts Institute of Technology',
    short_name: 'MIT',
    domain: 'mit.edu',
    logo_url: 'https://images.unsplash.com/photo-1564981797816-1043664bf78d?auto=format&fit=crop&w=400&q=80',
    description: 'Renowned institute focused on scientific and technological education.',
    location: 'Cambridge, MA, USA',
    is_active: true,
    course_count: 13,
  },
  {
    id: 'c0000000-0000-0000-0000-000000000003',
    name: 'University of California, Berkeley',
    short_name: 'UC Berkeley',
    domain: 'berkeley.edu',
    logo_url: 'https://images.unsplash.com/photo-1526778548025-fa2f459cd5c1?auto=format&fit=crop&w=400&q=80',
    description: 'Top global public university recognized for computer science and engineering.',
    location: 'Berkeley, CA, USA',
    is_active: true,
    course_count: 13,
  },
  {
    id: 'c0000000-0000-0000-0000-000000000004',
    name: 'Indian Institute of Technology Bombay',
    short_name: 'IIT Bombay',
    domain: 'iitb.ac.in',
    logo_url: 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?auto=format&fit=crop&w=400&q=80',
    description: 'Premier institute of technology in Mumbai, fostering high-impact engineering innovation.',
    location: 'Mumbai, India',
    is_active: true,
    course_count: 13,
  },
];

export const MOCK_CATEGORIES: Category[] = [
  {
    id: 'a0000000-0000-0000-0000-000000000001',
    name: 'Cloud Computing & AI',
    slug: 'cloud-ai',
    icon: 'Cloud',
    description: 'AWS, Google Cloud, Azure, generative AI models, and cloud infrastructure.',
    course_count: 5,
  },
  {
    id: 'a0000000-0000-0000-0000-000000000002',
    name: 'Developer Tools & IDEs',
    slug: 'dev-tools',
    icon: 'Code2',
    description: 'GitHub Developer Pack, JetBrains IDEs, AI Assistants, and version control.',
    course_count: 3,
  },
  {
    id: 'a0000000-0000-0000-0000-000000000003',
    name: 'Data Science & Analytics',
    slug: 'data-science',
    icon: 'Database',
    description: 'Big Data, Python analytics, SQL, IBM SkillsBuild, and Google Data Analytics.',
    course_count: 2,
  },
  {
    id: 'a0000000-0000-0000-0000-000000000004',
    name: 'Full-Stack & Web Development',
    slug: 'web-development',
    icon: 'Terminal',
    description: 'freeCodeCamp, responsive design, JavaScript, Python, and relational databases.',
    course_count: 2,
  },
  {
    id: 'a0000000-0000-0000-0000-000000000005',
    name: 'National & Academic Programs',
    slug: 'academic-programs',
    icon: 'Briefcase',
    description: 'NPTEL, SWAYAM, Infosys Springboard, Salesforce Trailhead, and HubSpot.',
    course_count: 3,
  },
];

export const MOCK_COURSES: Course[] = [
  {
    id: 'b0000000-0000-0000-0000-000000000001',
    slug: 'aws-student-rewards',
    title: 'AWS Student Rewards (brand new, Aug 2026)',
    provider: 'AWS Skill Builder',
    description: '12 months premium AWS Skill Builder (900+ cloud/AI courses) + a $100 voucher toward the AWS Certified Cloud Practitioner exam once you hit 21 community badges. Seven badges unlocks US$10 in AWS credits, 14 badges unlocks another US$20, and 21 badges unlocks an AWS Certification Foundational exam voucher worth US$100.',
    category: 'Cloud Computing & AI',
    level: 'Beginner',
    duration: '3–6 weeks (instant access)',
    certification_available: true,
    certificate_type: 'AWS Certified Cloud Practitioner Exam Voucher ($100 Value)',
    course_url: 'https://builder.aws.com',
    image_url: 'https://images.unsplash.com/photo-1607799279861-4dd421887fb3?auto=format&fit=crop&w=800&q=80',
    requirements: 'Yes — verification is handled through SheerID, with most checks completed within minutes; students must be 18 or over.',
    what_you_learn: [
      '12 months premium access to 900+ cloud and generative AI courses',
      'Earn community badges to unlock up to $30 in AWS cloud credits',
      'Receive a 100% discount $100 AWS Foundational Exam Voucher upon 21 badges',
      'Hands-on interactive AWS builder labs and architecture simulators'
    ],
    skills_gained: ['AWS', 'Cloud Architecture', 'IAM', 'EC2', 'S3', 'Generative AI on AWS'],
    is_free: true,
    is_active: true,
    is_featured: true,
    access_type: 'student_offer',
    verification_required: true,
    special_instructions: 'Sign up at builder.aws.com with student verification via SheerID (instant with college email or student ID).',
    click_count: 3820,
  },
  {
    id: 'b0000000-0000-0000-0000-000000000002',
    slug: 'github-student-developer-pack',
    title: 'GitHub Student Developer Pack',
    provider: 'GitHub Education',
    description: 'Not one certificate — a massive hub unlocking 100+ free partner tools & courses (JetBrains, Educative, MongoDB cert vouchers, free domain names, and cloud credits).',
    category: 'Developer Tools & IDEs',
    level: 'All Levels',
    duration: 'Approval in hours to days; courses vary',
    certification_available: true,
    certificate_type: 'Multiple Certification Vouchers & Pro Tier Badges',
    course_url: 'https://education.github.com/pack',
    image_url: 'https://images.unsplash.com/photo-1618401471353-b98afee0b2eb?auto=format&fit=crop&w=800&q=80',
    requirements: 'Yes — a school email address, plus a picture of your student ID for a higher chance of approval.',
    what_you_learn: [
      'Free GitHub Pro subscription and unlimited private repositories',
      'Free JetBrains All Products Pack subscription',
      'Free MongoDB certification exam vouchers and Educative courses',
      'Free cloud hosting credits on DigitalOcean and Microsoft Azure'
    ],
    skills_gained: ['Git', 'GitHub', 'Open Source', 'MongoDB', 'DevOps', 'Cloud Tools'],
    is_free: true,
    is_active: true,
    is_featured: true,
    access_type: 'college_email',
    verification_required: true,
    special_instructions: 'Apply on education.github.com/pack with your college email and student ID card for fast verification.',
    click_count: 4210,
  },
  {
    id: 'b0000000-0000-0000-0000-000000000003',
    slug: 'microsoft-certifications-az900-ai900',
    title: 'Microsoft Certifications (AZ-900, AI-900, DP-900)',
    provider: 'Microsoft Learn',
    description: 'Learning is always free; the exam itself ($99–165) is free during voucher windows. Microsoft Certification Week runs September 28 – October 2, 2026 — score 80% or higher on a LevelUp practice assessment and you get a free exam voucher.',
    category: 'Cloud Computing & AI',
    level: 'Beginner',
    duration: '~10–15 hrs self-paced',
    certification_available: true,
    certificate_type: 'Microsoft Certified Professional (AZ-900 / AI-900 Voucher)',
    course_url: 'https://learn.microsoft.com',
    image_url: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=800&q=80',
    requirements: 'Verified through Microsoft Learn student assessment portal with student email.',
    what_you_learn: [
      'Azure Cloud core concepts, architecture, and virtualization',
      'Artificial intelligence workloads, Computer Vision, and Azure OpenAI Service',
      'Data engineering fundamentals and relational databases in Azure',
      'Score 80%+ on LevelUp assessment to claim official 100% off voucher'
    ],
    skills_gained: ['Azure', 'AI-900', 'AZ-900', 'Cloud Architecture', 'Azure AI'],
    is_free: true,
    is_active: true,
    is_featured: true,
    access_type: 'student_offer',
    verification_required: true,
    special_instructions: 'Complete LevelUp practice assessment with 80%+ score on Microsoft Learn to claim the 100% off exam voucher.',
    click_count: 3120,
  },
  {
    id: 'b0000000-0000-0000-0000-000000000004',
    slug: 'jetbrains-student-pack',
    title: 'JetBrains Student Pack (All Products + AI Assistant)',
    provider: 'JetBrains',
    description: 'The full professional suite of JetBrains IDEs (IntelliJ IDEA Ultimate, PyCharm Pro, WebStorm, CLion) plus AI Assistant, Junie, and JetBrains Academy courses.',
    category: 'Developer Tools & IDEs',
    level: 'All Levels',
    duration: 'Renews yearly while enrolled',
    certification_available: true,
    certificate_type: 'JetBrains Academy Course Certificates & Professional Licenses',
    course_url: 'https://www.jetbrains.com/community/education',
    image_url: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&w=800&q=80',
    requirements: 'Yes — your university domain must be in JetBrains SWOT repository, or you can apply with a valid student ID / ISIC card.',
    what_you_learn: [
      'Master professional IDEs: IntelliJ IDEA, PyCharm, WebStorm, CLion',
      'AI Assistant code completion and refactoring features',
      'Project-based tracks on JetBrains Academy',
      'Yearly renewable full license for enrolled university students'
    ],
    skills_gained: ['Java', 'Python', 'Web Development', 'C++', 'IDEs', 'Debugging'],
    is_free: true,
    is_active: true,
    is_featured: true,
    access_type: 'college_email',
    verification_required: true,
    special_instructions: 'Enter your student email address on jetbrains.com/community/education. License key is generated instantly.',
    click_count: 2650,
  },
  {
    id: 'b0000000-0000-0000-0000-000000000005',
    slug: 'linkedin-learning-campus-access',
    title: 'LinkedIn Learning Campus Access',
    provider: 'LinkedIn Learning',
    description: 'Shareable completion certificates on 16,000+ expert-led courses across engineering, programming, product, and leadership.',
    category: 'Academic Programs',
    level: 'All Levels',
    duration: 'Most courses 1–4 hrs',
    certification_available: true,
    certificate_type: 'Shareable LinkedIn Learning Verified Certificates',
    course_url: 'https://www.linkedin.com/learning',
    image_url: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=800&q=80',
    requirements: 'Depends on college — many universities provide full student access via campus library or IT single sign-on.',
    what_you_learn: [
      'Over 16,000 expert-led courses updated weekly',
      'Earn certificates that attach automatically to your LinkedIn profile',
      'Topics range from Python, Cloud, Full-Stack to Technical Interview Prep',
      'Exercise files and practice quizzes included'
    ],
    skills_gained: ['LinkedIn Certificates', 'Software Engineering', 'Business', 'Project Management'],
    is_free: true,
    is_active: true,
    is_featured: false,
    access_type: 'institutional_access',
    verification_required: true,
    special_instructions: 'Sign in with your university single sign-on (SSO) on linkedin.com/learning to activate free institutional access.',
    click_count: 1980,
  },
  {
    id: 'b0000000-0000-0000-0000-000000000006',
    slug: 'google-cloud-skills-boost',
    title: 'Google Cloud Skills Boost & Generative AI Path',
    provider: 'Google Cloud',
    description: 'Free skill badges + a free 10-course Generative AI learning path. Learn directly on Google Cloud infrastructure with hands-on labs.',
    category: 'Cloud Computing & AI',
    level: 'Beginner',
    duration: 'Skill badges: 2–6 hrs each',
    certification_available: true,
    certificate_type: 'Google Cloud Skill Badges & Course Completion Credentials',
    course_url: 'https://www.cloudskillsboost.google',
    image_url: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=800&q=80',
    requirements: 'None for the free tier; college students receive lab credit waivers.',
    what_you_learn: [
      'Introduction to Generative AI, Large Language Models (LLMs)',
      'Prompt Design in Vertex AI',
      'Deploying models on Google Cloud Run and GKE',
      'Shareable Google Cloud Skill Badges for your resume'
    ],
    skills_gained: ['Google Cloud', 'Vertex AI', 'Generative AI', 'Prompt Engineering', 'LLMs'],
    is_free: true,
    is_active: true,
    is_featured: true,
    access_type: 'completely_free',
    verification_required: false,
    special_instructions: 'Sign up on cloudskillsboost.google and explore the free Generative AI learning path and student monthly credit grants.',
    click_count: 3410,
  },
  {
    id: 'b0000000-0000-0000-0000-000000000007',
    slug: 'coursera-financial-aid',
    title: 'Coursera — Financial Aid Route (Google, IBM & Meta Certs)',
    provider: 'Coursera',
    description: 'Google Data Analytics, IBM Data Science, Meta Marketing & other Professional Certificates, normally $49+/month, completely free via Financial Aid.',
    category: 'Data Science & Analytics',
    level: 'All Levels',
    duration: 'Single course 10–40 hrs; Professional Certificates 2–6 months',
    certification_available: true,
    certificate_type: 'Official Google, IBM & Meta Professional Certificates',
    course_url: 'https://www.coursera.org',
    image_url: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=800&q=80',
    requirements: 'Not student-specific — click "Financial Aid Available" on any course page. Reviewed and approved within ~15 days.',
    what_you_learn: [
      'Google Data Analytics Professional Certificate',
      'IBM Full Stack Software Developer Professional Certificate',
      'Meta Front-End & Back-End Developer Specializations',
      'Industry recognized credentials accepted by top recruiters'
    ],
    skills_gained: ['Data Analytics', 'Python', 'SQL', 'React', 'Full-Stack'],
    is_free: true,
    is_active: true,
    is_featured: true,
    access_type: 'scholarship',
    verification_required: false,
    special_instructions: 'On any course page, click "Financial Aid Available", enter student status, and your fee is waived to 100% free.',
    click_count: 2890,
  },
  {
    id: 'b0000000-0000-0000-0000-000000000008',
    slug: 'ibm-skillsbuild',
    title: 'IBM SkillsBuild (AI, Cybersecurity & Data Analytics)',
    provider: 'IBM SkillsBuild',
    description: 'Certificate pathways in AI, Cybersecurity, Data Analytics, IT Support, UX Design, and Software Engineering with verified Credly digital badges.',
    category: 'Cloud Computing & AI',
    level: 'Beginner',
    duration: 'Hours to a few weeks per pathway',
    certification_available: true,
    certificate_type: 'Official IBM Digital Credential (Credly)',
    course_url: 'https://skillsbuild.org',
    image_url: 'https://images.unsplash.com/photo-1507146426996-ef05306b995a?auto=format&fit=crop&w=800&q=80',
    requirements: 'No email gate — open to all college students at zero cost.',
    what_you_learn: [
      'Artificial Intelligence Fundamentals and Watson tools',
      'Cybersecurity analyst competencies and threat intelligence',
      'Data Analytics with Python, Excel, and IBM Cognos',
      'Enterprise Design Thinking credential'
    ],
    skills_gained: ['AI Fundamentals', 'Cybersecurity', 'Data Analytics', 'Python', 'IBM Credly'],
    is_free: true,
    is_active: true,
    is_featured: true,
    access_type: 'completely_free',
    verification_required: false,
    special_instructions: 'Register on skillsbuild.org. Completely free and available to all university students immediately.',
    click_count: 2420,
  },
  {
    id: 'b0000000-0000-0000-0000-000000000009',
    slug: 'salesforce-trailhead',
    title: 'Salesforce Trailhead (Badges & Superbadges)',
    provider: 'Salesforce',
    description: 'Free digital badges and Superbadges for your resume; prepares you for the official Salesforce Administrator & Developer proctored certifications.',
    category: 'Academic Programs',
    level: 'All Levels',
    duration: 'Roughly 60–100 hours of free modules to reach Admin-cert-ready',
    certification_available: true,
    certificate_type: 'Salesforce Superbadges & Resume Digital Credentials',
    course_url: 'https://trailhead.salesforce.com',
    image_url: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=800&q=80',
    requirements: 'No — free and open to anyone.',
    what_you_learn: [
      'Salesforce platform architecture, objects, and relationships',
      'Process automation using Salesforce Flow',
      'Apex programming and Lightning Web Components (LWC)',
      'Earning resume-boosting Superbadges that prove real-world skills'
    ],
    skills_gained: ['Salesforce', 'CRM', 'Apex', 'Flow', 'Lightning Components'],
    is_free: true,
    is_active: true,
    is_featured: false,
    access_type: 'completely_free',
    verification_required: false,
    special_instructions: 'Create a free account on trailhead.salesforce.com and follow the student Developer / Admin career trails.',
    click_count: 1450,
  },
  {
    id: 'b0000000-0000-0000-0000-000000000010',
    slug: 'hubspot-academy',
    title: 'HubSpot Academy (Inbound, SEO, Digital Marketing)',
    provider: 'HubSpot Academy',
    description: 'Free industry-recognized certifications with a passing exam and a downloadable, shareable credential — Marketing, Sales, SEO, Social Media, and CRM.',
    category: 'Academic Programs',
    level: 'Beginner',
    duration: 'A few hours to ~2 months',
    certification_available: true,
    certificate_type: 'Official HubSpot Industry Certificate & Digital Badge',
    course_url: 'https://academy.hubspot.com',
    image_url: 'https://images.unsplash.com/photo-1432888498266-38ffec3eaf0a?auto=format&fit=crop&w=800&q=80',
    requirements: 'No — 100% free for everyone, including exams and credentials.',
    what_you_learn: [
      'Inbound marketing methodology and content strategy',
      'Search Engine Optimization (SEO) fundamentals',
      'Email marketing, automation, and lead generation',
      'Pass online exam to download official verified certificates'
    ],
    skills_gained: ['Digital Marketing', 'SEO', 'Content Strategy', 'HubSpot CRM'],
    is_free: true,
    is_active: true,
    is_featured: false,
    access_type: 'completely_free',
    verification_required: false,
    special_instructions: 'Sign up on academy.hubspot.com. All exams, videos, and certificates are 100% free of charge.',
    click_count: 1620,
  },
  {
    id: 'b0000000-0000-0000-0000-000000000011',
    slug: 'freecodecamp-certifications',
    title: 'freeCodeCamp Full-Stack & Developer Certifications',
    provider: 'freeCodeCamp',
    description: 'Verified certifications in Responsive Web Design, JavaScript Algorithms, Python, Relational Databases, and Full-Stack Development.',
    category: 'Full-Stack & Web Development',
    level: 'All Levels',
    duration: 'Self-paced; full curriculum 300+ hrs per cert',
    certification_available: true,
    certificate_type: 'Verified freeCodeCamp Certification (Portfolio Verified)',
    course_url: 'https://www.freecodecamp.org',
    image_url: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?auto=format&fit=crop&w=800&q=80',
    requirements: 'No — free for everyone worldwide. Complete 5 required projects to earn verified certification.',
    what_you_learn: [
      'Responsive Web Design with HTML5, modern CSS, Flexbox, and Grid',
      'JavaScript Algorithms and Data Structures',
      'Front End Development Libraries (React, Redux, Bootstrap)',
      'Relational Databases with PostgreSQL and Bash'
    ],
    skills_gained: ['HTML5', 'CSS3', 'JavaScript', 'React', 'Python', 'PostgreSQL'],
    is_free: true,
    is_active: true,
    is_featured: true,
    access_type: 'completely_free',
    verification_required: false,
    special_instructions: 'Sign up on freecodecamp.org and start coding immediately in the browser.',
    click_count: 3650,
  },
  {
    id: 'b0000000-0000-0000-0000-000000000012',
    slug: 'infosys-springboard',
    title: 'Infosys Springboard (India & Global Students)',
    provider: 'Infosys Springboard',
    description: '20,000+ free courses and 6,600+ certifications across AI, data science, cybersecurity, Java, full-stack, and professional soft skills tailored for university undergraduates.',
    category: 'Academic Programs',
    level: 'Beginner',
    duration: 'Hours to weeks per track',
    certification_available: true,
    certificate_type: 'Official Infosys Springboard Verified Certificate of Completion',
    course_url: 'https://infyspringboard.onwingspan.com',
    image_url: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&w=800&q=80',
    requirements: 'No — open to all college students across India & worldwide.',
    what_you_learn: [
      'Comprehensive Java, Python, and Full-Stack Engineering curricula',
      'Artificial Intelligence, Machine Learning, and Cloud Fundamentals',
      'Corporate soft skills, resume building, and technical interview skills',
      'Course completion tests with automated instant certificates'
    ],
    skills_gained: ['Java', 'Python', 'Full-Stack', 'Cybersecurity', 'AI', 'Soft Skills'],
    is_free: true,
    is_active: true,
    is_featured: true,
    access_type: 'completely_free',
    verification_required: false,
    special_instructions: 'Register on infyspringboard.onwingspan.com using your personal or college email for instant access.',
    click_count: 2950,
  },
  {
    id: 'b0000000-0000-0000-0000-000000000013',
    slug: 'nptel-swayam-govt-india',
    title: 'NPTEL / SWAYAM (Govt. of India & IITs/IISc)',
    provider: 'NPTEL / SWAYAM',
    description: 'High-quality university courses taught by IIT and IISc professors. Learning and course materials are 100% free; proctored certificate exam is available with credit transfer support.',
    category: 'Academic Programs',
    level: 'All Levels',
    duration: '4, 8, or 12-week courses with assignments',
    certification_available: true,
    certificate_type: 'IIT / IISc Proctored Verified Certificate & College Credit Transfer',
    course_url: 'https://swayam.gov.in',
    image_url: 'https://images.unsplash.com/photo-1546410531-bb4caa6b424d?auto=format&fit=crop&w=800&q=80',
    requirements: 'Learning is completely free; the certificate proctored exam is ₹1,000 for NPTEL (or ₹500–750 for SWAYAM with SC/ST concession).',
    what_you_learn: [
      'In-depth engineering, computer science, and mathematics taught by IIT faculty',
      'Weekly graded assignments and interactive discussion forums with Teaching Assistants',
      'Academic bank of credits (ABC) transferable directly to your college degree',
      'Optionally take proctored exam in 100+ cities for hardcopy IIT verified credential'
    ],
    skills_gained: ['Data Structures', 'Computer Networks', 'Machine Learning', 'IIT Curriculum', 'Academic Credits'],
    is_free: true,
    is_active: true,
    is_featured: true,
    access_type: 'completely_free',
    verification_required: false,
    special_instructions: 'Enroll at swayam.gov.in or nptel.ac.in. College students can map courses for academic credit transfer.',
    click_count: 3880,
  },
];

// Campus Workshops & Hackathons Data
export const MOCK_WORKSHOPS: Workshop[] = [
  {
    id: 'ws-bmsit-01',
    college_id: 'c0000000-0000-0000-0000-000000000005', // BMSIT
    title: 'Hands-on Generative AI & Vertex AI Campus Workshop',
    organizer: 'Google Developer Student Clubs (GDSC) BMSIT & Dept. of CSE',
    description: 'Live coding boot camp on building Retrieval-Augmented Generation (RAG) models, prompt engineering, and LLM applications using Google Cloud Vertex AI. Free lunch and Google Cloud swags provided.',
    date: 'Saturday, Sept 26, 2026',
    time: '10:00 AM - 4:30 PM IST',
    venue: 'BMSIT Main Seminar Hall, Academic Block 1, Bangalore',
    mode: 'In-Person',
    registration_url: 'https://bmsit.in',
    instructor: 'Google Developer Expert (AI/ML)',
    is_active: true,
    tags: ['Generative AI', 'Vertex AI', 'Free Swags', 'Hands-on'],
    college_name: 'BMS Institute of Technology (BMSIT)',
  },
  {
    id: 'ws-bmsit-02',
    college_id: 'c0000000-0000-0000-0000-000000000005', // BMSIT
    title: 'AWS Cloud Day: Practitioner Bootcamp & $100 Voucher Drop',
    organizer: 'Dept. of Information Science & Engineering (ISE) x AWS Academy',
    description: 'Hands-on architectural sandbox session on EC2, S3, IAM, and serverless architectures. All participating BMSIT students receive guidance on unlocking their $100 AWS certification voucher.',
    date: 'Wednesday, Oct 7, 2026',
    time: '2:00 PM - 5:30 PM IST',
    venue: 'Tech Hub Lab 4, 3rd Floor, BMSIT Campus',
    mode: 'In-Person',
    registration_url: 'https://bmsit.in',
    instructor: 'AWS Certified Solutions Architect',
    is_active: true,
    tags: ['AWS', 'Cloud', '$100 Voucher', 'Hands-on Lab'],
    college_name: 'BMS Institute of Technology (BMSIT)',
  },
  {
    id: 'ws-bmsit-03',
    college_id: 'c0000000-0000-0000-0000-000000000005', // BMSIT
    title: 'Cybersecurity Incident Response & Capture The Flag (CTF)',
    organizer: 'BMSIT Cyber Security Cell & Cisco Networking Academy',
    description: 'Live Wireshark packet inspection, defensive host analysis, firewall rule configuration, and introductory CTF challenges with certificate of participation.',
    date: 'Friday, Oct 16, 2026',
    time: '9:30 AM - 3:00 PM IST',
    venue: 'BMSIT Auditorium & Hybrid Online Stream',
    mode: 'Hybrid',
    registration_url: 'https://bmsit.in',
    instructor: 'Senior SOC Security Specialist',
    is_active: true,
    tags: ['Cybersecurity', 'CTF', 'Wireshark', 'Certificate'],
    college_name: 'BMS Institute of Technology (BMSIT)',
  },
  {
    id: 'ws-bmsit-04',
    college_id: 'c0000000-0000-0000-0000-000000000005', // BMSIT
    title: 'GitHub Campus Day & Open Source Hackathon',
    organizer: 'GitHub Campus Experts @ BMSIT',
    description: 'Demystifying Open Source contributions: branch management, PR workflows, automated tests with GitHub Actions, and 1-on-1 assistance claiming the GitHub Student Developer Pack.',
    date: 'Saturday, Oct 24, 2026',
    time: '11:00 AM - 5:00 PM IST',
    venue: 'BMSIT Open Air Amphitheatre',
    mode: 'In-Person',
    registration_url: 'https://bmsit.in',
    instructor: 'GitHub Campus Expert',
    is_active: true,
    tags: ['Open Source', 'GitHub Pack', 'Hackathon'],
    college_name: 'BMS Institute of Technology (BMSIT)',
  },
  {
    id: 'ws-iitb-01',
    college_id: 'c0000000-0000-0000-0000-000000000004', // IIT Bombay
    title: 'NPTEL & Deep Learning Workshop',
    organizer: 'KReSIT & Computer Center IIT Bombay',
    description: 'Advanced deep learning seminar and assignment preparation for NPTEL credit transfer.',
    date: 'Saturday, Oct 10, 2026',
    time: '10:00 AM - 2:00 PM IST',
    venue: 'F.C. Kohli Auditorium, IIT Bombay',
    mode: 'In-Person',
    registration_url: 'https://iitb.ac.in',
    instructor: 'IITB Faculty & Research Scholars',
    is_active: true,
    tags: ['Deep Learning', 'NPTEL', 'IIT Bombay'],
    college_name: 'IIT Bombay',
  },
  {
    id: 'ws-stanford-01',
    college_id: 'c0000000-0000-0000-0000-000000000001', // Stanford
    title: 'Stanford AI & Cloud Computing Hackathon',
    organizer: 'Stanford Computer Science Department',
    description: 'Annual campus hackathon with free Google Cloud and AWS credit grants for all enrolled students.',
    date: 'Friday, Oct 30, 2026',
    time: '9:00 AM - 6:00 PM PST',
    venue: 'Huang Engineering Center, Stanford Campus',
    mode: 'In-Person',
    registration_url: 'https://stanford.edu',
    instructor: 'Stanford CS Faculty',
    is_active: true,
    tags: ['Hackathon', 'AI', 'Cloud Credits'],
    college_name: 'Stanford University',
  }
];

// College to Course mappings
export const MOCK_COLLEGE_COURSES: Record<string, { course_id: string; access_type: AccessType; special_instructions: string }[]> = {
  // BMSIT - All 13 courses mapped!
  'c0000000-0000-0000-0000-000000000005': MOCK_COURSES.map((c) => ({
    course_id: c.id,
    access_type: c.access_type || 'college_email',
    special_instructions: `Verified for BMSIT students. Use your @bmsit.in email or student ID card to claim free access.`,
  })),

  // Stanford University
  'c0000000-0000-0000-0000-000000000001': MOCK_COURSES.map((c) => ({
    course_id: c.id,
    access_type: c.access_type || 'college_email',
    special_instructions: `Verified for Stanford students via @stanford.edu single sign-on.`,
  })),

  // MIT
  'c0000000-0000-0000-0000-000000000002': MOCK_COURSES.map((c) => ({
    course_id: c.id,
    access_type: c.access_type || 'college_email',
    special_instructions: `Verified for MIT students via @mit.edu domain.`,
  })),

  // UC Berkeley
  'c0000000-0000-0000-0000-000000000003': MOCK_COURSES.map((c) => ({
    course_id: c.id,
    access_type: c.access_type || 'college_email',
    special_instructions: `Verified for UC Berkeley students via @berkeley.edu CalNet portal.`,
  })),

  // IIT Bombay
  'c0000000-0000-0000-0000-000000000004': MOCK_COURSES.map((c) => ({
    course_id: c.id,
    access_type: c.access_type || 'college_email',
    special_instructions: `Verified for IIT Bombay students via @iitb.ac.in institute email.`,
  })),
};
