import { Creator, UIProduct, UICategory } from '@/types/marketplace';

export const MOCK_CREATORS: Record<string, Creator> = {
  'creator-1': {
    id: 'creator-1',
    display_name: 'Sarah Lin',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80',
    bio: 'Staff Product Designer & AI Engineer. Ex-Vercel, building developer-first generative interfaces.',
    verified: true,
    total_sales: 342,
    rating: 4.96,
  },
  'creator-2': {
    id: 'creator-2',
    display_name: 'David K.',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80',
    bio: 'Fintech UI Architect & Data Visualization specialist. Crafting dense, high-performance dashboards.',
    verified: true,
    total_sales: 518,
    rating: 4.92,
  },
  'creator-3': {
    id: 'creator-3',
    display_name: 'Elena Rostova',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=200&q=80',
    bio: 'Design Systems Lead. Passionate about typography, minimal aesthetics, and student developer portfolios.',
    verified: true,
    total_sales: 427,
    rating: 4.98,
  },
  'creator-4': {
    id: 'creator-4',
    display_name: 'Marcus Vance',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80',
    bio: 'AI Product Designer. Focused on canvas interfaces, token streams, and multi-model chat workspaces.',
    verified: true,
    total_sales: 289,
    rating: 4.88,
  },
  'creator-5': {
    id: 'creator-5',
    display_name: 'Priya Nair',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=200&q=80',
    bio: 'Headless E-commerce Engineer. Built storefronts driving $10M+ in GMV. Speed & conversion focused.',
    verified: true,
    total_sales: 194,
    rating: 4.95,
  },
  'creator-6': {
    id: 'creator-6',
    display_name: 'Alex Chen',
    avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=200&q=80',
    bio: 'Stanford Open Source Fellow & Hackathon Mentor. Helping students turn ideas into launch-ready MVPs.',
    verified: true,
    total_sales: 612,
    rating: 4.97,
  },
};

export const MOCK_UI_PRODUCTS: UIProduct[] = [
  {
    id: 'ui-prod-001',
    title: 'AI SaaS Landing Page & Workflow Studio',
    slug: 'ai-saas-landing-page',
    description:
      'High-converting landing page crafted for next-gen AI startups. Features dark mode bento grid, interactive prompt input mockup, animated benchmark metrics, and pricing tiers.',
    category: 'SaaS',
    price: 299,
    currency: 'INR',
    preview_image:
      'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=1200&q=80',
    gallery_images: [
      'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=1200&q=80',
    ],
    live_demo_url: 'https://demo.cosurf.dev/marketplace/ai-saas',
    creator_id: 'creator-1',
    technologies: ['Next.js', 'React', 'Tailwind', 'TypeScript', 'Framer Motion'],
    features: [
      'Bento grid layout with subtle borders and radial glow effects',
      'Interactive AI prompt demo widget with simulated token streaming',
      'Monthly/Annual pricing toggle with highlighted recommended tier',
      'Testimonial marquee with developer quotes and avatar stack',
      'Mobile-responsive navigation drawer with smooth backdrop blur',
    ],
    components_included: [
      'HeroWithPromptInput',
      'BentoFeatureGrid',
      'InteractiveAIPromptWidget',
      'PricingTierTable',
      'FaqAccordion',
      'TestimonialMarquee',
      'CtaBanner',
    ],
    license_type: 'Commercial',
    status: 'published',
    responsive: true,
    rating: 4.96,
    reviews_count: 84,
    sales_count: 342,
    is_featured: true,
    is_trending: true,
    created_at: '2026-08-15T10:00:00Z',
    updated_at: '2026-09-12T14:30:00Z',
  },
  {
    id: 'ui-prod-002',
    title: 'Modern Analytics & Observability Dashboard',
    slug: 'modern-analytics-dashboard',
    description:
      'Executive-grade data dashboard designed for enterprise observability and metrics. Includes real-time line charts, conversion funnel graphs, server health status cards, and date-range filtering.',
    category: 'Dashboards',
    price: 399,
    currency: 'INR',
    preview_image:
      'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=1200&q=80',
    gallery_images: [
      'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1504868584819-f8e8b4b6d7e3?auto=format&fit=crop&w=1200&q=80',
    ],
    live_demo_url: 'https://demo.cosurf.dev/marketplace/analytics',
    creator_id: 'creator-2',
    technologies: ['React', 'TypeScript', 'Tailwind', 'Shadcn UI', 'Next.js'],
    features: [
      'Dense data layout with toggleable compact mode',
      'Multi-axis revenue & token consumption time series chart',
      'Drill-down user cohorts table with pagination and sorting',
      'Quick KPI stat cards with trend badges (+14.2% MoM)',
      'Export modal for CSV/JSON reports',
    ],
    components_included: [
      'SidebarNav',
      'HeaderWithDateRange',
      'StatSummaryCards',
      'TimeSeriesChartCard',
      'CohortDataTable',
      'HealthStatusWidget',
    ],
    license_type: 'Commercial',
    status: 'published',
    responsive: true,
    rating: 4.92,
    reviews_count: 67,
    sales_count: 518,
    is_featured: true,
    is_trending: false,
    created_at: '2026-08-20T11:00:00Z',
    updated_at: '2026-09-14T09:15:00Z',
  },
  {
    id: 'ui-prod-003',
    title: 'Developer Minimalist Portfolio & Tech Blog',
    slug: 'developer-portfolio',
    description:
      'Clean, typography-centered portfolio for software engineers and computer science students. Showcases GitHub repository cards, pinned open-source contributions, interactive terminal bio, and MDX articles.',
    category: 'Portfolios',
    price: 199,
    currency: 'INR',
    preview_image:
      'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?auto=format&fit=crop&w=1200&q=80',
    gallery_images: [
      'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=1200&q=80',
    ],
    live_demo_url: 'https://demo.cosurf.dev/marketplace/portfolio',
    creator_id: 'creator-3',
    technologies: ['Next.js', 'Tailwind', 'TypeScript', 'HTML/CSS'],
    features: [
      'Interactive pseudo-CLI terminal widget with runnable commands',
      'Grid of featured projects with live deployment and GitHub stars',
      'Reading time indicator and table of contents for technical essays',
      'Work experience timeline with collapsible impact bullet points',
      'Instant copy email button with subtle toast feedback',
    ],
    components_included: [
      'TerminalBioWidget',
      'ProjectShowcaseCard',
      'ExperienceTimeline',
      'BlogArticleCard',
      'TechStackIconGrid',
      'FooterSocialBar',
    ],
    license_type: 'Personal',
    status: 'published',
    responsive: true,
    rating: 4.98,
    reviews_count: 92,
    sales_count: 427,
    is_featured: false,
    is_trending: true,
    created_at: '2026-08-25T08:00:00Z',
    updated_at: '2026-09-15T16:00:00Z',
  },
  {
    id: 'ui-prod-004',
    title: 'AI Chat & Multi-Modal Agent Canvas',
    slug: 'ai-chat-application',
    description:
      'State-of-the-art conversational UI tailored for AI agents, multi-step reasoning models, and code generation. Includes split canvas view, code diff inspector, branch switcher, and prompt template sidebar.',
    category: 'AI Websites',
    price: 299,
    currency: 'INR',
    preview_image:
      'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=1200&q=80',
    gallery_images: [
      'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&w=1200&q=80',
    ],
    live_demo_url: 'https://demo.cosurf.dev/marketplace/ai-chat',
    creator_id: 'creator-4',
    technologies: ['React', 'Next.js', 'Tailwind', 'TypeScript', 'Shadcn UI'],
    features: [
      'Split-screen artifact view (Chat on left, Live Rendered Code on right)',
      'Syntax highlighted code blocks with one-click copy and line numbering',
      'Thinking process accordion with expandable reasoning steps',
      'Model picker dropdown (GPT, Claude, Gemini, DeepSeek)',
      'Token counter and latency indicator badges',
    ],
    components_included: [
      'ChatSidebarHistory',
      'MessageStreamList',
      'ReasoningStepsAccordion',
      'ArtifactPreviewCanvas',
      'CodeDiffBlock',
      'ModelSelectorModal',
    ],
    license_type: 'Commercial',
    status: 'published',
    responsive: true,
    rating: 4.88,
    reviews_count: 53,
    sales_count: 289,
    is_featured: true,
    is_trending: true,
    is_new: true,
    created_at: '2026-09-01T12:00:00Z',
    updated_at: '2026-09-18T18:00:00Z',
  },
  {
    id: 'ui-prod-005',
    title: 'Headless E-commerce Storefront & Checkout Flow',
    slug: 'ecommerce-storefront',
    description:
      'Ultra-fast headless commerce template designed for digital goods, hardware gadgets, and merchandise. Includes faceted filter drawer, 3-step checkout drawer, and customer reviews with photo upload preview.',
    category: 'E-commerce',
    price: 499,
    currency: 'INR',
    preview_image:
      'https://images.unsplash.com/photo-1472851294608-062f824d29cc?auto=format&fit=crop&w=1200&q=80',
    gallery_images: [
      'https://images.unsplash.com/photo-1472851294608-062f824d29cc?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1556742049-0a67e557224f?auto=format&fit=crop&w=1200&q=80',
    ],
    live_demo_url: 'https://demo.cosurf.dev/marketplace/ecommerce',
    creator_id: 'creator-5',
    technologies: ['Next.js', 'React', 'Tailwind', 'TypeScript'],
    features: [
      'Sticky bottom cart bar on mobile for high conversion',
      'Product gallery with zoom magnifier and thumbnail carousel',
      'Slide-over slideout cart with promo code input',
      'Color and size variant selector pills with stock status',
      'Optimized 1-page checkout accordion layout',
    ],
    components_included: [
      'ProductGridCard',
      'FilterSidebarDrawer',
      'ProductImageGallery',
      'SlideOverCart',
      'CheckoutAccordion',
      'ReviewListWithPhotos',
    ],
    license_type: 'Extended Commercial',
    status: 'published',
    responsive: true,
    rating: 4.95,
    reviews_count: 41,
    sales_count: 194,
    is_featured: false,
    is_trending: false,
    created_at: '2026-08-10T14:00:00Z',
    updated_at: '2026-09-08T11:20:00Z',
  },
  {
    id: 'ui-prod-006',
    title: 'Student Project Showcase & Research Lab Hub',
    slug: 'student-project-dashboard',
    description:
      'Built specifically for college hackathons, capstone projects, and university research laboratories. Features paper citation cards, contributor grids, dataset download drawers, and live project status badges.',
    category: 'Student Projects',
    price: 149,
    currency: 'INR',
    preview_image:
      'https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&w=1200&q=80',
    gallery_images: [
      'https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1531403009284-440f080d1e12?auto=format&fit=crop&w=1200&q=80',
    ],
    live_demo_url: 'https://demo.cosurf.dev/marketplace/student-hub',
    creator_id: 'creator-6',
    technologies: ['React', 'Tailwind', 'TypeScript', 'HTML/CSS'],
    features: [
      'BibTeX citation generator modal with 1-click copy',
      'Faculty advisor & student author credit badges',
      'Interactive benchmark scoreboard comparing model accuracies',
      'Embedded video / slide deck presentation modal',
      'Downloadable research artifacts and PDF links',
    ],
    components_included: [
      'ProjectOverviewHero',
      'AuthorCreditStack',
      'CitationCopyModal',
      'BenchmarkScoreTable',
      'DatasetAssetList',
      'HackathonAwardBadge',
    ],
    license_type: 'Personal',
    status: 'published',
    responsive: true,
    rating: 4.97,
    reviews_count: 118,
    sales_count: 612,
    is_featured: true,
    is_trending: true,
    created_at: '2026-08-01T09:00:00Z',
    updated_at: '2026-09-17T15:40:00Z',
  },
  {
    id: 'ui-prod-007',
    title: 'Mobile-First Neo-Banking & Expense Tracker UI',
    slug: 'mobile-fintech-app',
    description:
      'Touch-optimized mobile interface for modern fintech apps, expense splitters, and student budget trackers. Features swipeable balance cards, spending category donuts, and biometric unlock mockup.',
    category: 'Mobile UI',
    price: 349,
    currency: 'INR',
    preview_image:
      'https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format&fit=crop&w=1200&q=80',
    gallery_images: [
      'https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1559526324-4b87b5e36e44?auto=format&fit=crop&w=1200&q=80',
    ],
    live_demo_url: 'https://demo.cosurf.dev/marketplace/mobile-fintech',
    creator_id: 'creator-2',
    technologies: ['React', 'TypeScript', 'Tailwind', 'Framer Motion'],
    features: [
      'Mobile viewport container with native-feeling spring physics',
      'Virtual debit card carousel with flip-to-reveal CVV animation',
      'Monthly spending category breakdown with interactive progress bars',
      'Peer-to-peer quick send transfer sheet with student avatar circles',
      'Transaction history filterable by date, type, and merchant',
    ],
    components_included: [
      'MobileFrameContainer',
      'VirtualCardCarousel',
      'QuickSendAvatarBar',
      'SpendingBreakdownWidget',
      'TransactionFeedItem',
      'BottomNavigationTab',
    ],
    license_type: 'Commercial',
    status: 'published',
    responsive: true,
    rating: 4.91,
    reviews_count: 36,
    sales_count: 178,
    is_featured: false,
    is_trending: false,
    is_new: true,
    created_at: '2026-09-05T15:00:00Z',
    updated_at: '2026-09-19T10:00:00Z',
  },
  {
    id: 'ui-prod-008',
    title: 'DevKit UI: Accessible Component Library & Docs System',
    slug: 'devkit-component-system',
    description:
      '100% Free developer toolkit including 24+ accessible primitives, code copy snippets, live component playground, and dark mode design tokens. Perfect starter for your AI projects.',
    category: 'Full Website Kits',
    price: 0, // FREE!
    currency: 'INR',
    preview_image:
      'https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?auto=format&fit=crop&w=1200&q=80',
    gallery_images: [
      'https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1461749280684-dccba630e2f6?auto=format&fit=crop&w=1200&q=80',
    ],
    live_demo_url: 'https://demo.cosurf.dev/marketplace/devkit',
    creator_id: 'creator-6',
    technologies: ['React', 'Next.js', 'Tailwind', 'TypeScript', 'HTML/CSS'],
    features: [
      'Completely free to claim and use in personal or commercial projects',
      'Interactive component playground with live prop controls',
      'Pre-built Buttons, Dialogs, Tooltips, Accordions, Tabs, and Inputs',
      'WAI-ARIA compliant keyboard navigation and screen reader labels',
      'One-click CLI install commands and Tailwind configuration',
    ],
    components_included: [
      'DocsSidebar',
      'ComponentPlayground',
      'CodeSnippetViewer',
      'PropsTable',
      'TokenColorPalette',
      'CalloutAlert',
    ],
    license_type: 'MIT',
    status: 'published',
    responsive: true,
    rating: 4.99,
    reviews_count: 245,
    sales_count: 1420,
    is_featured: true,
    is_trending: true,
    created_at: '2026-07-20T10:00:00Z',
    updated_at: '2026-09-16T12:00:00Z',
  },
];

export const UI_CATEGORIES: UICategory[] = [
  'AI Websites',
  'SaaS',
  'Dashboards',
  'Portfolios',
  'E-commerce',
  'Admin Panels',
  'Landing Pages',
  'Authentication',
  'Pricing Pages',
  'Student Projects',
  'Mobile UI',
  'Full Website Kits',
];
